
#ifndef __INSTRUCTION_H__
#define __INSTRUCTION_H__

typedef enum {
    INST_NOP,
    INST_LD,
    INST_LDI,
    INST_LDD,
    INST_INC,
    INST_DEC,
    INST_RLCA,
    INST_ADD,
    INST_RRCA,
    INST_STOP,
    INST_RLA,
    INST_JR,
    INST_JR_Z,
    INST_JR_NZ,
    INST_JR_C,
    INST_JR_NC,
    INST_RRA,
    INST_DAA,
    INST_CPL,
    INST_SCF,
    INST_CCF,
    INST_ADC,
    INST_SUB,
    INST_SBC,
    INST_AND,
    INST_XOR,
    INST_OR,
    INST_CP,
    INST_RET,
    INST_RETI,
    INST_RET_Z,
    INST_RET_NZ,
    INST_RET_NC,
    INST_POP,
    INST_JP,
    INST_JP_Z,
    INST_JP_NZ,
    INST_JP_C,
    INST_JP_NC,
    INST_CALL,
    INST_CALL_Z,
    INST_CALL_NZ,
    INST_CALL_NC,
    INST_PUSH,
    INST_RST,
    INST_PREFIX,
    INST_LDH,
    INST_DI,
    INST_EI,
    INST_HALT,
} instruction_e;

#endif /* __INSTRUCTION_H__ */
